### PR TITLE
[FRONT-684] Use OCR client

### PR DESCRIPTION
**Pull request by juhah**
Needs https://github.com/streamr-dev/streamr-client-react/pull/3 from `streamr-client-react`. Instructions to use:

1. clone `streamr-client-react` and checkout `ocr-client` branch
2. Run `npm ci && npm run build`
3. Run `npm link`

In `core-front-end`:

1. Install dependencies with `npm ci`
2. Link `streamr-client-react` with `npm link streamr-client-react`
3. Run `npm start`

Docker setup

Update to latest version from `streamr-docker-dev` `master` branch, you may have to do a factory-reset to remove existing images.

You can test that streams are coming from registry by going to 
http://localhost:8000/subgraphs/name/streamr-dev/network-contracts/graphql and try the query `{nodes {id}}`:

```json
{
  "data": {
    "nodes": [
      {
        "id": "0xde1112f631486cfc759a50196853011528bc5fa0"
      }
    ]
  }
}
```

Or streams (when you have created some):
Screenshot 2021-11-30 at 14 03 01

**NOTE:** If you experience transactions pending forever or otherwise mysteriously failing, try resetting the account in Metamask (it gets messed up if the network gets restarted).

### CODE REVIEW

**Comment by mondoreale** [comment]
Aaight, taking over!

**Comment by mondoreale** [comment]
Synced with `development`.

**Comment by mondoreale** [comment]
Extracted some updates and renaming into indep commits. Already in `development`. Will make it as dense as possible, with features related exclusively to OCR.

**Comment by tumppi** [comment]
I'm getting this error with your new changes:

```
ERROR in Flow: Type Error

Error --------------------------------------- node_modules/resolve/test/resolver/malformed_package_json/package.json:2:1

Unexpected end of input, expected the token }

     1| {
     2|
```

**Comment by tumppi** [comment]
@mondoreale: I added a new hook `useRequireNetwork` to show a modal when we are on wrong chain.

**Comment by mondoreale** [comment]
@tumppi, sounds good. A question! Can it be separated from this PR? I know it's been part of this PR for a while (wanted to extract it, too). It feels like a feature that's unrelated to OCR. LMK

**Comment by tumppi** [comment]
> @tumppi, sounds good. A question! Can it be separated from this PR? I know it's been part of this PR for a while (wanted to extract it, too). It feels like a feature that's unrelated to OCR. LMK

You mean the whole wrong chain dialog thingy? It could be separated but it seems to be a huge spider web so it'd be quite a task to achieve. I'd say it's not worth extracting it. If you are talking just about my changes (adding the hook and refactoring usage), then I could just cherry pick that commit into another PR if needed.

**Comment by mondoreale** [comment]
Closing this one. Let's continue in [`brubeck`](https://github.com/streamr-dev/core-frontend/pull/1297) aka #1297.

**Pull request closed without merging**
