### PR TITLE
[FRONT-187] Use detectFields from streamr-client

### PR DESCRIPTION
**Pull request by tumppi**
Removes unsupported API calls for stream field detection and uses the feature from `streamr-client`.

### CODE REVIEW

**Review by juhah — COMMENTED** [review]
Maybe we should a save before clicking "Autodetect fields"? It does a save after detecting and will lose any edits if you have added fields.

**Comment by juhah** [comment]
Also it gives a console error after detecting fields:
Screenshot 2021-04-15 at 9 56 26

Looks like the id is generated with `uuid()` on the frontend side, would need to do that again after we get the fields back from the client I guess.

**Comment by tumppi** [comment]
> Maybe we should do a save before clicking "Autodetect fields"? It does a save after detecting and will lose any edits if you have added fields.

The autodetection feature will overwrite fields anyway so probably no need to do a save.

**Review by juhah — APPROVED** [review]
Works nicely now, could you still clean up the unused reducer states `autodetectFetching` and `streamFieldAutodetectError` + the related selectors.

The `autodetectFetching` was used to disable the form while loading so that can either be removed or implemented in another way.

**Pull request merged**
