### PR TITLE
add key exchange doc

### PR DESCRIPTION
**Pull request by mthambipillai**

### CODE REVIEW

**Comment by mthambipillai** [comment]
Added documentation about revocation as well since it should be done soon (done for Java client, PR open for JS client).

**Comment by fonty1** [comment]
@hpihkala - can this be merged soon?

**Comment by hpihkala** [comment]
@fonty1 not very soon unfortunately. The explicit inbox stream management didn’t work out, so we need to pivot a bit. The work is in progress but will take a few weeks at least. Let’s hold this for now. If we’re aiming for a docs release without any todos (good idea), the encryption section can be removed/hidden until this is good to go.

**Comment by mondoreale** [comment]
Is this PR worth bringing back to live? Got closed by gh because of no `development` branch.

**Pull request closed without merging**
