### PR TITLE
[FRONT-1421][FRONT-1426] Configure webpack to optimize bundle size

### PR DESCRIPTION
**Pull request by tumppi**
Just by adding `Terser` we get a decent 50% improvement in bundle sizes.

Before:

- main: **992kb** (199kb gzipped)
- vendor: **19.4mb** (4.3mb gzipped)

After:

- main: **489kb** (126kb gzipped)
- vendor: **10.3mb** (2.8mb gzipped)

### CODE REVIEW

**Comment by mondoreale** [comment]
Screenshot 2023-05-24 at 1 48 03 PM

Strange. It looks like altho fonts are loaded the layout doesn't know (some elements).

**Comment by tumppi** [comment]
True. Maybe related to tree shaking. I'll investigate more.

**Comment by tumppi** [comment]
Had to disable tree shaking. We are not ready for that yet. Anyway the win would have been only a couple of kilobytes so not worth banging our heads to the wall :)

**Comment by tumppi** [comment]
This also fixes [FRONT-1426](https://linear.app/streamr/issue/FRONT-1426/introduce-a-tool-to-detect-unused-exports])

**Pull request merged**
