### PR TITLE
Add LogStore as a storage provider

### PR DESCRIPTION
**Pull request by victorshevtsov**

### CODE REVIEW

**Review by mondoreale — COMMENTED** [review]
@victorshevtsov, can you rename `thirdPartyLink` to `thirdPartyUrl`? My thinking:
- "Link" is more like the actual `<a>`, and
- URL is a low level value one'd use for anchor's `href` attribute.

All good otherwise, cheers!

**Comment by victorshevtsov** [comment]
> @victorshevtsov, can you rename `thirdPartyLink` to `thirdPartyUrl`? My thinking:
> 
> * "Link" is more like the actual `<a>`, and
> * URL is a low level value one'd use for anchor's `href` attribute.
> 
> All good otherwise, cheers!

Definitely, `Url` much better denotes the meaning of the field. This is a good point. Changed.
Cheers!

**Comment by mondoreale** [comment]
Thank you @victorshevtsov!

**Comment by mondoreale** [comment]
It's live (landed in `v4.10.0`). Cheers!

**Comment by victorshevtsov** [comment]
Thank you @mondoreale !

**Pull request merged**
