### PR TITLE
Update JS client link to the (new) monorepo

### PR DESCRIPTION
**Pull request by translate3d**

### CODE REVIEW

**Comment by juhah** [comment]
@translate3d Thanks for the PR, though there will need to be a more thorough cleaning of the client links to point to the monorepo. cc @fonty1

**Comment by fonty1** [comment]
@mxinburritos - can you scan through these `core-frontend` docs and make sure all the JS client links point to the new monorepo? You can commit to this PR and add me as a reviewer when you're done :)

**Comment by mxinburritos** [comment]
I updated all of the JS client and cli tools links. I think all of the other links to the GitHub aren't in the monorepo. Once @translate3d signs the CLA, we can merge it.

**Comment by fonty1** [comment]
Thanks all, this was helpful - the fixes were applied in a separate PR, so closing this one.

**Pull request closed without merging**
