### PR TITLE
Terminology and copy updates

### PR DESCRIPTION
**Pull request by fonty1**
- Add help texts everywhere
- Updated a lot of the terminology
- Made some context sensitive copy alternatives here and there..

**Terminology updated:**
- Operator’s cut -> Owner’s cut
- Total value -> Total stake
- Operator ID -> Operator
- Operator contract -> Operator (in most cases)
- Operator name -> Operator (in most cases)
- Deposit -> Fund

If the operator owner is logged in  {
  Deposit / Delegate -> Fund
  Undelegate -> Withdraw
  My delegation -> My stake
}

@mondoreale - the Delegate/Undelegate modals need a copy update to be context sensitive to the owner being the logged in user - Can you take that over and drive from here?

### CODE REVIEW

**Comment by mondoreale** [comment]
Sure!

**Comment by mondoreale** [comment]
Polished it a bit, replaced static `DATA` with the dynamic token symbol in a couple of places. Unblobbed some texts, too. Example:

Screenshot 2023-10-26 at 5 19 18 PM

I'm gonna work on the"Become Operator" modal changes tomorrow. Looks like there's a need for a little bit of clean up there anyway, generally.

Will keep u posted!

**Comment by fonty1** [comment]
> Screenshot 2023-10-26 at 5 19 18 PM

Looks muchos better!

I would just start those bullet points with, 

**A Redundancy Factor of 1**...

~~setting it to 2..~~ **A Redundancy Factor of 2**...

**Comment by mondoreale** [comment]
Screenshot 2023-10-27 at 11 54 53 AM

**Comment by mondoreale** [comment]
Some of the changes
- Both "Delegate funds" and "Undelegate funds" modal dialogs got refactored for better DX.
- `useDelegateFunds` and `useUndelegateFunds` – hooks that drive "Delegate" and "Undelegate" buttons – return sync callbacks. Nothing `async` about them anymore = it's no longer required to catch any errors coming out of those callbacks or decorate them in any way. They just work.
- Clicking "Delegate" / "Undelegate" button will no longer prematurely trigger "Switch to correct network" modal dialog. Now it's gonna be displayed if the user is on the incorrect network right before the transaciton.
- Rejecting transactions, rejecting the corrective network switch, etc. will no longer dismiss the associated modal. Instead users will be able to retry w.o entering everything again. (Only delegate/undelegate modals for now.)
- And of course the copy, mostly code formatting.

There are few more smaller extras. All in all, things got smoother.

**Review by mondoreale — APPROVED** [review]
😉

**Comment by mondoreale** [comment]
@fonty1 I'll push it to staging. Let's have another PR (or ticket) for another round of these. Cheers!

**Pull request merged**
