### PR TITLE
Net 719 docs update broker instructions

### PR DESCRIPTION
**Pull request by kare**
depends on v32 Broker release

### CODE REVIEW

**Comment by hpihkala** [comment]
@kare what's the status of this PR please?

**Comment by kare** [comment]
@hpihkala It needs described changes to broker and tracker Docker containers.

**Comment by hpihkala** [comment]
@kare do if you know if the change is:
- Implemented but not released as docker
- Not implemented?

**Comment by kare** [comment]
> @kare do if you know if the change is:
> 
> * Implemented but not released as docker
> * Not implemented?

@hpihkala It exists, but wasn't merged after all: https://github.com/streamr-dev/network-monorepo/pull/500

**Comment by hpihkala** [comment]
> It exists, but wasn't merged after all: [streamr-dev/network-monorepo#500](https://github.com/streamr-dev/network-monorepo/pull/500)

@kare The PR you linked _is_ merged though?

**Comment by kare** [comment]
It's not in main branch and tracker requires same treatment.

**Review by fonty1 — APPROVED** [review]

**Pull request merged**
